version: '3.8'

services:
  se-server:
    build: .
    image: se-dedicated-srv:latest
    container_name: se-dedicated-srv
    restart: unless-stopped
    volumes:
      - ./se-server/:/se-server
    ports:
      - target: 8080
        published: 18080
        protocol: tcp
        mode: host
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment: 
      - WINEDEBUG=-all
