version: "3.7"
services:
  ######## Space Engineers Server########
  se-dedicated-srv:
    restart: "no"
    image: se-dedicated-srv:latest
    volumes:
      - ./se-server:/se-server
    ports:
     - "27016:27016/udp"
    # networks:
    #   server-network:
    #       ipv4_address: 172.24.2.1

volumes:
  se-server:
